version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quartz-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/public:/usr/share/nginx/html:ro
      - ./app/private/js:/opt/app-private/js:ro
      - ./nginx/public.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: quartz-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./nginx/ssl:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email alex.quartzcs@gmail.com --agree-tos --no-eff-email
      -d quartzcs.com -d www.quartzcs.com"
